# Generated by Django 4.2.7 on 2023-11-28 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleticas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atletica',
            name='tipo_usuario',
            field=models.CharField(default='ATL', max_length=3),
        ),
    ]
