# Generated by Django 4.2.7 on 2023-11-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleticas', '0003_alter_atletica_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atletica',
            name='logo',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
