# Generated by Django 4.2.7 on 2023-11-24 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunos', '0003_alter_aluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curso_academico',
            field=models.CharField(max_length=3, verbose_name='Curso Acadêmico'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Endereço de Email'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='nome_completo',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status_monitor',
            field=models.BooleanField(default=False, verbose_name='Status de Monitor'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
