# Generated by Django 4.2.7 on 2023-11-15 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('data_lancamento', models.DateField(auto_now_add=True)),
                ('curso_academico_relacionado', models.CharField(max_length=3)),
                ('thumbnail', models.ImageField(upload_to='static/thumbs_cursos')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_modulo', models.CharField(max_length=50)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='cursos.curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
            },
        ),
        migrations.CreateModel(
            name='Videoaula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_video', models.CharField(max_length=100)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('titulo_descricao', models.CharField(max_length=50)),
                ('descricao_video', models.TextField(max_length=300)),
                ('url_video', models.URLField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videoaulas', to='cursos.modulo')),
            ],
            options={
                'verbose_name': 'Videoaula',
                'verbose_name_plural': 'Videoaulas',
            },
        ),
    ]
