# Generated by Django 4.2.7 on 2023-11-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoaula',
            name='titulo_descricao',
        ),
    ]
