# Generated by Django 4.2.7 on 2023-11-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_videoaula_titulo_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='thumbnail',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
