# Lista de Cursos de Bacharelado, Licenciatura, Especialização, MBA, Mestrado e Doutorado da UCSal
OPCOES_CURSOS = [
    ('ADM', 'Administração'),
    ('ANC', 'Análises Clínicas'),
    ('ADS', 'Análise e Desenvolvimento de Sistemas'),
    ('ARQ', 'Arquitetura e Urbanismo'),
    ('APG', 'Assessoria Política e Governo'),
    ('BMD', 'Biomedicina'),
    ('BIO', 'Ciências Biológicas'),
    ('CTB', 'Ciências Contábeis'),
    ('CCR', 'Ciências Criminais'),
    ('COM', 'Comunicação e Marketing Digital'),
    ('DSI', 'Design de Interiores'),
    ('DIR', 'Direito (Bacharelado)'),
    ('DIM', 'Direito (Mestrado)'),
    ('DEL', 'Direito Eleitoral'),
    ('DFS', 'Direito das Famílias e Sucessões'),
    ('DPR', 'Direito Previdenciário Teoria e Prática'),
    ('DPM', 'Direito Público Municipal'),
    ('DTB', 'Direito Tributário'),
    ('DGE', 'Docência e Gestão Escolar'),
    ('EDF', 'Educação Física'),
    ('ENF', 'Enfermagem'),
    ('CIV', 'Engenharia Civil'),
    ('MEC', 'Engenharia Mecânica'),
    ('EST', 'Engenharia da Segurança do Trabalho'),
    ('SFT', 'Engenharia de Software'),
    ('QMC', 'Engenharia Química'),
    ('FSD', 'Família na Sociedade Contemporânea (Doutorado)'),
    ('FSM', 'Família na Sociedade Contemporânea (Mestrado)'),
    ('FIL', 'Filosofia'),
    ('FIS', 'Fisioterapia'),
    ('GST', 'Gastronomia'),
    ('GEO', 'Geografia'),
    ('GTC', 'Gestão Comercial'),
    ('GEI', 'Gestão Empreendedora e Inovação em Negócios Digitais'),
    ('GTF', 'Gestão Financeira'),
    ('GPE', 'Gestão de Pessoas'),
    ('GPR', 'Gestão de Projetos'),
    ('GPU', 'Gestão Pública'),
    ('GTQ', 'Gestão de Qualidade'),
    ('GQA', 'Gestão da Qualidade e Acreditação em Saúde'),
    ('GRH', 'Gestão de Recursos Humanos'),
    ('GTI', 'Gestão da Tecnologia da Informação'),
    ('HIS', 'História'),
    ('HBA', 'História da Bahia'),
    ('JOG', 'Jogos Digitais'),
    ('JOR', 'Jornalismo'),
    ('LOG', 'Logística'),
    ('LAE', 'Logoterapia e Análise Existencial'),
    ('LTI', 'Letras Inglês'),
    ('LTP', 'Letras Português'),
    ('MKT', 'Marketing'),
    ('MKD', 'Marketing Digital'),
    ('MAT', 'Matemática'),
    ('MSP', 'Música - Piano'),
    ('MSV', 'Música - Violão'),
    ('NUT', 'Nutrição'),
    ('PDG', 'Pedagogia'),
    ('SCD', 'Políticas Sociais e Cidadania (Doutorado)'),
    ('SCM', 'Políticas Sociais e Cidadania (Mestrado)'),
    ('PSI', 'Psicologia'),
    ('PJM', 'Psicologia Jurídica e Mediação de Conflitos'),
    ('PPC', 'Psicologia e Práticas Clínicas'),
    ('PUB', 'Publicidade e Propaganda'),
    ('RLP', 'Relações Públicas'),
    ('SGI', 'Segurança da Informação'),
    ('JCN', 'Serviços Jurídicos, Cartorários e Notariais'),
    ('SVS', 'Serviço Social'),
    ('TEO', 'Teologia'),
    ('TAD', 'Território, Ambiente e Sociedade (Doutorado)'),
    ('TAM', 'Território, Ambiente e Sociedade (Mestrado)'),
    ('TJA', 'Tribunal do Júri e Audiência de Custódia'),
]
